INSTAGRAM_USERNAME: "tu_usuario_de_instagram"
INSTAGRAM_PASSWORD: "tu_contraseña_de_instagram"
INSTAGRAM_TARGET_USERNAME: "nombre_de_usuario_del_destinatario"
SUPERAGI_API_KEY: "tu_clave_de_api_de_superagi"

